export const SELLER_ORDER_CREATE_REQUEST = 'SELLER_ORDER_CREATE_REQUEST';
export const SELLER_ORDER_CREATE_SUCCESS = 'SELLER_ORDER_CREATE_SUCCESS';
export const SELLER_ORDER_CREATE_FAIL = 'SELLER_ORDER_CREATE_FAIL';

export const SELLER_ORDER_LIST_REQUEST = 'SELLER_ORDER_LIST_REQUEST';
export const SELLER_ORDER_LIST_SUCCESS = 'SELLER_ORDER_LIST_SUCCESS';
export const SELLER_ORDER_LIST_FAIL = 'SELLER_ORDER_LIST_FAIL';

export const SELLER_ORDER_MY_LIST_REQUEST = 'SELLER_ORDER_MY_LIST_REQUEST';
export const SELLER_ORDER_MY_LIST_SUCCESS = 'SELLER_ORDER_MY_LIST_SUCCESS';
export const SELLER_ORDER_MY_LIST_FAIL = 'SELLER_ORDER_MY_LIST_FAIL';

export const SELLER_ORDER_MY_UNPAID_LIST_REQUEST = 'SELLER_ORDER_MY_UNPAID_LIST_REQUEST';
export const SELLER_ORDER_MY_UNPAID_LIST_SUCCESS = 'SELLER_ORDER_MY_UNPAID_LIST_SUCCESS';
export const SELLER_ORDER_MY_UNPAID_LIST_FAIL = 'SELLER_ORDER_MY_UNPAID_LIST_FAIL';

export const SELLER_ORDER_DETAILS_REQUEST = 'SELLER_ORDER_DETAILS_REQUEST';
export const SELLER_ORDER_DETAILS_SUCCESS = 'SELLER_ORDER_DETAILS_SUCCESS';
export const SELLER_ORDER_DETAILS_FAIL = 'SELLER_ORDER_DETAILS_FAIL';

export const SELLER_ORDER_DISCARD_REQUEST = 'SELLER_ORDER_DISCARD_REQUEST';
export const SELLER_ORDER_DISCARD_SUCCESS = 'SELLER_ORDER_DISCARD_SUCCESS';
export const SELLER_ORDER_DISCARD_FAIL = 'SELLER_ORDER_DISCARD_FAIL';

export const SELLER_ORDER_DELIVER_REQUEST = 'SELLER_ORDER_DELIVER_REQUEST';
export const SELLER_ORDER_DELIVER_SUCCESS = 'SELLER_ORDER_DELIVER_SUCCESS';
export const SELLER_ORDER_DELIVER_FAIL = 'SELLER_ORDER_DELIVER_FAIL';
export const SELLER_ORDER_DELIVER_RESET = 'SELLER_ORDER_DELIVER_RESET';

export const SELLER_ORDER_PAY_REQUEST = 'SELLER_ORDER_PAY_REQUEST';
export const SELLER_ORDER_PAY_SUCCESS = 'SELLER_ORDER_PAY_SUCCESS';
export const SELLER_ORDER_PAY_FAIL = 'SELLER_ORDER_PAY_FAIL';
export const SELLER_ORDER_PAY_RESET = 'SELLER_ORDER_PAY_RESET';
